#!/bin/sh

ROOT_DIR=/app

replace_env_var() {
  local env_var=$1
  local placeholder=$2
  local default_value=$3
  env_var=${env_var:-$default_value}
  for file in $ROOT_DIR/js/*.js* $ROOT_DIR/index.html $ROOT_DIR/precache-manifest*.js;
    do
        sed -i "s|$placeholder|$env_var|g" $file
        done
}

# Replace env vars in files served by NGINX
replace_env_var "$VUE_APP_SERVER_BASE_URL" "VUE_APP_SERVER_BASE_URL_PLACEHOLDER"
replace_env_var "$VUE_APP_NAME" "VUE_APP_NAME_PLACEHOLDER"
replace_env_var "$VUE_APP_IS_PRODUCTION" "VUE_APP_IS_PRODUCTION_PLACEHOLDER"

# Theme colors for the light theme
replace_env_var "$VUE_APP_PRIMARY_COLOR" "VUE_APP_PRIMARY_COLOR_PLACEHOLDER" "#0099DB"
replace_env_var "$VUE_APP_SECONDARY_COLOR" "VUE_APP_SECONDARY_COLOR_PLACEHOLDER" "#FFCC00"
replace_env_var "$VUE_APP_ACCENT_COLOR" "VUE_APP_ACCENT_COLOR_PLACEHOLDER" "#e5f5fc"
replace_env_var "$VUE_APP_ERROR_COLOR" "VUE_APP_ERROR_COLOR_PLACEHOLDER" "#FF5252"
replace_env_var "$VUE_APP_INFO_COLOR" "VUE_APP_INFO_COLOR_PLACEHOLDER" "#2196F3"
replace_env_var "$VUE_APP_SUCCESS_COLOR" "VUE_APP_SUCCESS_COLOR_PLACEHOLDER" "#4CAF50"
replace_env_var "$VUE_APP_WARNING_COLOR" "VUE_APP_WARNING_COLOR_PLACEHOLDER" "#FB8C00"
replace_env_var "$VUE_APP_BODY_COLOR" "VUE_APP_BODY_COLOR_PLACEHOLDER" "#707070"
replace_env_var "$VUE_APP_DARKGREY_COLOR" "VUE_APP_DARKGREY_COLOR_PLACEHOLDER" "#3b3b3b"

# Theme colors for the dark theme
replace_env_var "$VUE_APP_PRIMARY_COLOR_DARK" "VUE_APP_PRIMARY_COLOR_DARK_PLACEHOLDER" "#0099DB"
replace_env_var "$VUE_APP_SECONDARY_COLOR_DARK" "VUE_APP_SECONDARY_COLOR_DARK_PLACEHOLDER" "#FFCC00"
replace_env_var "$VUE_APP_ACCENT_COLOR_DARK" "VUE_APP_ACCENT_COLOR_DARK_PLACEHOLDER" "#282828"
replace_env_var "$VUE_APP_ERROR_COLOR_DARK" "VUE_APP_ERROR_COLOR_DARK_PLACEHOLDER" "#FF5252"
replace_env_var "$VUE_APP_INFO_COLOR_DARK" "VUE_APP_INFO_COLOR_DARK_PLACEHOLDER" "#2196F3"
replace_env_var "$VUE_APP_SUCCESS_COLOR_DARK" "VUE_APP_SUCCESS_COLOR_DARK_PLACEHOLDER" "#4CAF50"
replace_env_var "$VUE_APP_WARNING_COLOR_DARK" "VUE_APP_WARNING_COLOR_DARK_PLACEHOLDER" "#FB8C00"
replace_env_var "$VUE_APP_BODY_COLOR_DARK" "VUE_APP_BODY_COLOR_DARK_PLACEHOLDER" "#707070"
replace_env_var "$VUE_APP_DARKGREY_COLOR_DARK" "VUE_APP_DARKGREY_COLOR_DARK_PLACEHOLDER" "#f5f5f5"

# Starting NGINX
nginx -g 'daemon off;'
