#!/bin/sh

ROOT_DIR=/app

# Replace env vars in files served by NGINX
for file in $ROOT_DIR/js/*.js* $ROOT_DIR/index.html $ROOT_DIR/precache-manifest*.js;
do
  sed -i "s|VUE_APP_SERVER_BASE_URL_PLACEHOLDER|$VUE_APP_SERVER_BASE_URL|g" $file
  sed -i "s|VUE_APP_NAME_PLACEHOLDER|$VUE_APP_NAME|g" $file
  sed -i "s|VUE_APP_IS_PRODUCTION_PLACEHOLDER|$VUE_APP_IS_PRODUCTION|g" $file

  # Theme colors for the light theme
  sed -i "s|VUE_APP_PRIMARY_COLOR_PLACEHOLDER|$VUE_APP_PRIMARY_COLOR|g" $file
  sed -i "s|VUE_APP_SECONDARY_COLOR_PLACEHOLDER|$VUE_APP_SECONDARY_COLOR|g" $file
  sed -i "s|VUE_APP_ACCENT_COLOR_PLACEHOLDER|$VUE_APP_ACCENT_COLOR|g" $file
  sed -i "s|VUE_APP_ERROR_COLOR_PLACEHOLDER|$VUE_APP_ERROR_COLOR|g" $file
  sed -i "s|VUE_APP_INFO_COLOR_PLACEHOLDER|$VUE_APP_INFO_COLOR|g" $file
  sed -i "s|VUE_APP_SUCCESS_COLOR_PLACEHOLDER|$VUE_APP_SUCCESS_COLOR|g" $file
  sed -i "s|VUE_APP_WARNING_COLOR_PLACEHOLDER|$VUE_APP_WARNING_COLOR|g" $file
  sed -i "s|VUE_APP_BODY_COLOR_PLACEHOLDER|$VUE_APP_BODY_COLOR|g" $file
  sed -i "s|VUE_APP_DARKGREY_COLOR_PLACEHOLDER|$VUE_APP_DARKGREY_COLOR|g" $file

  # Theme colors for the dark theme
  sed -i "s|VUE_APP_PRIMARY_COLOR_DARK_PLACEHOLDER|$VUE_APP_PRIMARY_COLOR_DARK|g" $file
  sed -i "s|VUE_APP_SECONDARY_COLOR_DARK_PLACEHOLDER|$VUE_APP_SECONDARY_COLOR_DARK|g" $file
  sed -i "s|VUE_APP_ACCENT_COLOR_DARK_PLACEHOLDER|$VUE_APP_ACCENT_COLOR_DARK|g" $file
  sed -i "s|VUE_APP_ERROR_COLOR_DARK_PLACEHOLDER|$VUE_APP_ERROR_COLOR_DARK|g" $file
  sed -i "s|VUE_APP_INFO_COLOR_DARK_PLACEHOLDER|$VUE_APP_INFO_COLOR_DARK|g" $file
  sed -i "s|VUE_APP_SUCCESS_COLOR_DARK_PLACEHOLDER|$VUE_APP_SUCCESS_COLOR_DARK|g" $file
  sed -i "s|VUE_APP_WARNING_COLOR_DARK_PLACEHOLDER|$VUE_APP_WARNING_COLOR_DARK|g" $file
  sed -i "s|VUE_APP_DARKGREY_COLOR_DARK_PLACEHOLDER|$VUE_APP_DARKGREY_COLOR_DARK|g" $file
done
# Starting NGINX
nginx -g 'daemon off;'
